services:
  monitor:
    build: .
    image: health-monitor:v1
    container_name: health-system-app
    network_mode: "host"
    pid: "host"
    environment:
      - TERM=xterm-256color
    volumes:
      - /proc:/proc:ro
      - /sys:/sys:ro
      - ./logs:/var/log/
    stdin_open: true
    tty: true
